apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ngrok-ingress-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://ngrok.github.io/kubernetes-ingress-controller
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ngrok-ingress-controller
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
