apiVersion: v1
kind: Service
metadata:
  name: game-2048
  namespace: ngrok-ingress-controller
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: game-2048
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  namespace: ngrok-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
        - name: backend
          image: alexwhen/docker-2048
          ports:
            - name: http
              containerPort: 80
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: game-2048-ingress
#   namespace: ngrok-ingress-controller
#   annotations:
#     k8s.ngrok.com/modules: oauth-and-circuit-breaking
# spec:
#   ingressClassName: ngrok
#   rules:
#     - host: pheasant-closing-wolf.ngrok-free.app
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: game-2048
#                 port:
#                   number: 80
# ---
# # Module configurations for Circuit Breaking and OAuth
# kind: NgrokModuleSet
# apiVersion: ingress.k8s.ngrok.com/v1alpha1
# metadata:
#   name: oauth-and-circuit-breaking
#   namespace: ngrok-ingress-controller
# modules:
#   circuitBreaker:
#     trippedDuration: 10s
#     rollingWindow: 10s
#     numBuckets: 10
#     volumeThreshold: 20
#     errorThresholdPercentage: "0.50"
