apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: guestbook-ui
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: guestbook-ingress
#   annotations:
#     konghq.com/strip-path: "true"
# spec:
#   ingressClassName: kong
#   rules:
#   - host: 1f86-103-165-227-170.ngrok-free.app
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: guestbook-ui
#             port:
#               number: 80
