# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: index-html-configmap1.yaml
#   namespace: default
# data:
#   index.html: |
#     <html>
#     <h1> Welcome there! This is Deployment One, acting as the clothing 👔 and accessories 👓 website. </h1>
#     </html
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - name: app-port
          containerPort: 80
        # volumeMounts:
        #     - name: nginx-index-file
        #       mountPath: usr/share/nginx/html/index.html
        #       subPath: index.html
        # volume:
        #   - name: nginx-index-file
        #     cofigMap:
        #       name: index-html-configmap1.yaml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
    - name: svc-port
      port: 80
      targetPort: app-port
      protocol: TCP
  selector:
    app: nginx
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80